version: '2'

services:
    proxy:
      image: traefik
      command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
      ports:
        - "80:80"
        - "8080:8080"
      networks:
        - webgateway
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml
      labels:
          - "traefik.enable=false"
    nginx:
       image: nginx:latest
       networks:
         - webgateway
       volumes:
         - ./nginx_home:/nginx_home
         - ./default.conf:/etc/nginx/conf.d/default.conf
       labels:
        - "traefik.backend=nginx"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip: /boo"

networks:
  webgateway:
    driver: bridge
