version: '2'

services:

    proxy:
      image: traefik
      command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
      ports:
        - "2370:2370"
      networks:
        - webgateway
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml

    consul:
        image: consul
        restart: always
        ports:
          - "8600"
          - "53"

    nginx:
       image: nginx:stable
       ports:
         - "8080:80"
       volumes:
        - ./nginx_home:/nginx_home
        - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  webgateway:
    driver: bridge
