version: '2'

services:
#
#Proxy using Traefik to handle ingress traffic
#
    proxy:
      image: traefik
      command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
      ports:
        - "80:80"
        - "8080:8080"
      networks:
        - webgateway
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml
      labels:
        - "traefik.enable=false"

#
#Service Discovery using Consul
#
    servicediscovery:
      image: consul
      command: consul agent -dev -client 127.0.0.1
      networks:
        - webgateway
      ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
      expose:
        - "8300"
        - "8301"
        - "8301/udp"
        - "8302"
        - "8302/udp"
        - "8500"

#
#Service Register to have containers automatically register with consul
#
    registrator:
      image: gliderlabs/registrator:master
      command:  -internal consul://127.0.0.1:8500
      links:
        - servicediscovery
      networks:
        - webgateway
      depends_on:
        - servicediscovery
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock

#
#Webserver using Nginx
#
    webserver:
       image: nginx:latest
       links:
         - servicediscovery
       networks:
         - webgateway
       volumes:
         - ./nginx_home:/nginx_home
         - ./default.conf:/etc/nginx/conf.d/default.conf
       labels:
        - "traefik.backend=nginx"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip: /boo"

networks:
  webgateway:
    driver: bridge
