version: '2'

services:
#
#Proxy using Traefik to handle ingress traffic
#
    proxy:
      image: traefik
      command: --web --docker --docker.domain=docker.localhost
      ports:
        - "80:80"
        - "8080:8080"
      labels:
        - "traefik.enable=false"

#
#Service Discovery using Consul
#services:
    servicediscovery:
      image: consul
      command: consul agent -ui --server --bootstrap --client 0.0.0.0 --data-dir=/tmp/consul
      ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:8600"
      expose:
        - "8300"
        - "8301"
        - "8301/udp"
        - "8302"
        - "8302/udp"
        - "8500"
#
#Automatic Service Discovery
#

    registrator:
      image: gliderlabs/registrator
      command: -internal consul://servicediscovery:8500
      restart: on-failure


#
#Webserver using Nginx
#
    webserver:
       image: nginx:latest
       links:
         - servicediscovery
       volumes:
         - ./var/www/html:/var/www/html
         - ./default.conf:/etc/nginx/conf.d/default.conf
       labels:
        - "traefik.backend=nginx"
        - "traefik.port="
        - "traefik.frontend.rule=PathPrefixStrip: /boo"

    phpfpm:
      image: php:7-fpm
      volumes:
        - ./var/www/html:/var/www/html
